version: '3'

services:
  nginx:
    image: nginx
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/site.conf
    depends_on:
      - php
    environment:
      DNSDOCK_ALIAS: utf8.docker
      DOCUMENT_ROOT: /var/www/html/public
      INDEX_FILE: index.php
      PHP_FPM_SOCKET: php:9000


  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      DNSDOCK_ALIAS: mysql.utf8.docker
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: utf8

  php:
    image: hermsi/alpine-fpm-php
    volumes:
      - ./:/var/www/html
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa:ro
      - ~/.composer:/root/.composer
      - /tmpfs
    working_dir: /var/www/html
    environment:
      PHP_FPM_USER: root
    depends_on:
      - mysql
